version: "2.4"

services:
  postgresql:
    image: "postgres:11.5"
    ports:
      - "15432:5432"
    volumes:
      - "./postgresql/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: cadmium
      POSTGRES_PASSWORD: cadmium
      POSTGRES_DB: cadmium
    user: ${USER_ID}